### ISSUE TITLE
Assertion failure in `examples/notify_store_retrieve.c`

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#105]
Every once in a while, the `notify_store_retrieve` example fails as follows:

```
test/test_examples.py::test_notify1[True-notify_inval_inode] PASSED
test/test_examples.py::test_notify1[True-notify_store_retrieve] FAILED

====================================== FAILURES =======================================
______________________ test_notify1[True-notify_store_retrieve] _______________________
Traceback (most recent call last):
  File "/home/nikratio/in-progress/libfuse/test/test_examples.py", line 171, in test_notify1
    umount(mount_process, mnt_dir)
  File "/home/nikratio/in-progress/libfuse/test/util.py", line 51, in umount
    pytest.fail('file system process terminated with code %s' % (code,))
  File "/home/nikratio/.local/lib/python3.4/site-packages/_pytest/runner.py", line 486, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: file system process terminated with code -9
-------------------------------- Captured stderr call ---------------------------------
lt-notify_store_retrieve: notify_store_retrieve.c:317: update_fs_loop: Assertion `fuse_lowlevel_notify_store(se, 2, 0, &bufv, 0) == 0' failed.
!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!
======================== 1 failed, 13 passed in 25.89 seconds =========================
```

**Comment by Nikratio** [comment]
I think the problem is that the `notify..()` call may be executed when the file system has already been unmounted.
