### ISSUE TITLE
test: tst_utimens fails, OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by murthyanish** [libfuse/libfuse#230]
Hi,
I just installed Fuse, and tried testing it, but get the below error.
I've tried editing the `test_examples.py` file to track down the problem, and it seems calling `os.utime(filename, None, ns=(atime_ns, mtime_ns))` causes a problem. It doesn't seem to give a problem on inserting a location on my computer manually, so it seems to have something to do with `filename`.

```
alkove@TheAlkove-KU-1:~/USP Lab/fuse-3.2.1/fuse-3.2.1/make$ sudo python3 -m pytest test/
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.5.2, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3
cachedir: test/.cache
rootdir: /home/alkove/USP Lab/fuse-3.2.1/fuse-3.2.1/make/test, inifile: pytest.ini
collected 29 items                                                                                                                                                                             

test/test_ctests.py::test_write_cache[False] PASSED                                                                                                                                      [  3%]
test/test_ctests.py::test_write_cache[True] PASSED                                                                                                                                       [  6%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                                                                                                                        [ 10%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                                                                                                                           [ 13%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                                                                                                                     [ 17%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                                                                                                                       [ 20%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                                                                                                                          [ 24%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                                                                                                                    [ 27%]
test/test_ctests.py::test_notify_file_size[True] PASSED                                                                                                                                  [ 31%]
test/test_ctests.py::test_notify_file_size[False] PASSED                                                                                                                                 [ 34%]
test/test_examples.py::test_hello[hello-options0] PASSED                                                                                                                                 [ 37%]
test/test_examples.py::test_hello[hello-options1] PASSED                                                                                                                                 [ 41%]
test/test_examples.py::test_hello[hello_ll-options0] PASSED                                                                                                                              [ 44%]
test/test_examples.py::test_hello[hello_ll-options1] PASSED                                                                                                                              [ 48%]
test/test_examples.py::test_passthrough_ll[False-False] PASSED                                                                                                                           [ 51%]
test/test_examples.py::test_passthrough_ll[False-True] PASSED                                                                                                                            [ 55%]
test/test_examples.py::test_passthrough_ll[True-False] PASSED                                                                                                                            [ 58%]
test/test_examples.py::test_passthrough_ll[True-True] PASSED                                                                                                                             [ 62%]
test/test_examples.py::test_passthrough[False-passthrough] FAILED                                                                                                                        [ 65%]
=================================================================================== short test summary info ====================================================================================
FAIL test/test_examples.py::test_passthrough[False-passthrough]

=========================================================================================== FAILURES ===========================================================================================
_____________________________________________________________________________ test_passthrough[False-passthrough] ______________________________________________________________________________
Traceback (most recent call last):
  File "/home/alkove/USP Lab/fuse-3.2.1/fuse-3.2.1/make/test/test_examples.py", line 154, in test_passthrough
    tst_utimens(work_dir, ns_tol=1000)
  File "/home/alkove/USP Lab/fuse-3.2.1/fuse-3.2.1/make/test/test_examples.py", line 592, in tst_utimens
    os.utime(filename, None, ns=(atime_ns, mtime_ns))
OSError: [Errno 38] Function not implemented
============================================================================= 1 failed, 18 passed in 21.13 seconds =============================================================================
```

Thanks in advance!

**Comment by Nikratio** [comment]
Thanks for the report! What's your kernel version?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
