### ISSUE TITLE
test suite fails with pytest 3.7

### ISSUE THREAD

**Issue by ncopa** [libfuse/libfuse#293]
````
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 19, in <module>
    import _pytest.hookspec  # the extension point definitions
  File "/usr/lib/python3.6/site-packages/_pytest/hookspec.py", line 27, in <module>
    @hookspec(historic=True, warn_on_impl=PYTEST_NAMESPACE)
TypeError: __call__() got an unexpected keyword argument 'warn_on_impl'
````

Seems like the deprecation of pytest_namespace is related:
https://docs.pytest.org/en/latest/changelog.html#deprecations-and-removals

**Comment by Nikratio** [comment]
Thanks for the report! Unfortunately none of the files in the traceback above belong into libfuse, so this really isn't related to libfuse at all.
