### ISSUE TITLE
Unable to execute pytest correctly

### ISSUE THREAD

**Issue by Roay** [libfuse/libfuse#325]
`# sudo python3 -m pytest test/`
```
====================================== test session starts =======================================
platform linux -- Python 3.6.5, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /bin/python3
cachedir: test/.pytest_cache
rootdir: /root/roay/build/test, inifile: pytest.ini
collected 41 items                                                                               

test/test_ctests.py::test_write_cache[False] PASSED                                        [  2%]
test/test_ctests.py::test_write_cache[True] PASSED                                         [  4%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                          [  7%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                             [  9%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                       [ 12%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                         [ 14%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                            [ 17%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                      [ 19%]
test/test_ctests.py::test_notify_file_size[True] PASSED                                    [ 21%]
test/test_ctests.py::test_notify_file_size[False] PASSED                                   [ 24%]
test/test_examples.py::test_hello[hello-options0-invoke_directly] PASSED                   [ 26%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse] PASSED                 [ 29%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges] PASSED [ 31%]
test/test_examples.py::test_hello[hello-options1-invoke_directly] PASSED                   [ 34%]
test/test_examples.py::test_hello[hello-options1-invoke_mount_fuse] PASSED                 [ 36%]
test/test_examples.py::test_hello[hello-options1-invoke_mount_fuse_drop_privileges] PASSED [ 39%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_directly] PASSED                [ 41%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_mount_fuse] PASSED              [ 43%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_mount_fuse_drop_privileges] PASSED [ 46%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_directly] PASSED                [ 48%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_mount_fuse] PASSED              [ 51%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_mount_fuse_drop_privileges] PASSED [ 53%]
test/test_examples.py::test_passthrough[False-passthrough-False] FAILED                    [ 56%]

============================================ FAILURES ============================================
___________________________ test_passthrough[False-passthrough-False] ____________________________
Traceback (most recent call last):
  File "/root/roay/build/test/test_examples.py", line 148, in test_passthrough
    subprocess.check_call(syscall_test_cmd)
  File "/opt/Python/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/roay/build/test/../test/test_syscalls', '/tmp/pytest-of-root/pytest-2/test_passthrough_False_passthr0/mnt/tmp/pytest-of-root/pytest-2/test_passthrough_False_passthr0/src', ':/tmp/pytest-of-root/pytest-2/test_passthrough_False_passthr0/src']' returned non-zero exit status 1.
-------------------------------------- Captured stderr call --------------------------------------
  1 [create] OK
  2 [create+unlink] OK
  3 [symlink] OK
  4 [link] OK
  5 [link-unlink-link] OK
  6 [mknod] OK
  7 [mkfifo] OK
  8 [mkdir] OK
  9 [rename file] OK
 10 [rename dir] OK
 11 [rename dir loop] test_rename_dir_loop() - rename: File exists
 12 [seekdir] OK
 13 [utime] OK
 14 [truncate(0)] OK
 15 [truncate(13)] OK
 16 [truncate(26)] OK
 17 [truncate(126)] OK
 18 [ftruncate(0) mode: 0600] OK
 19 [ftruncate(13) mode: 0600] OK
 20 [ftruncate(26) mode: 0600] OK
 21 [ftruncate(126) mode: 0600] OK
 22 [ftruncate(0) mode: 0400] OK
 23 [ftruncate(0) mode: 0200] OK
 24 [ftruncate(0) mode: 0000] OK
 25 [open(-, O_RDONLY, 0000)] OK
 26 [open(+, O_RDONLY, 0000)] OK
 27 [open(+, O_RDWR, 0000)] OK
 28 [open(+, O_WRONLY, 0000)] OK
 29 [open(-, O_RDWR | O_CREAT, 0600)] OK
 30 [open(+, O_RDWR | O_CREAT, 0600)] OK
 31 [open(-, O_RDWR | O_CREAT | O_TRUNC, 0600)] OK
 32 [open(+, O_RDWR | O_CREAT | O_TRUNC, 0600)] OK
 33 [open(-, O_RDONLY | O_CREAT, 0600)] OK
 34 [open(-, O_RDONLY | O_CREAT, 0400)] OK
 35 [open(-, O_RDONLY | O_CREAT, 0200)] OK
 36 [open(-, O_RDONLY | O_CREAT, 0000)] OK
 37 [open(-, O_WRONLY | O_CREAT, 0600)] OK
 38 [open(-, O_WRONLY | O_CREAT, 0400)] OK
 39 [open(-, O_WRONLY | O_CREAT, 0200)] OK
 40 [open(-, O_WRONLY | O_CREAT, 0000)] OK
 41 [open(-, O_RDWR | O_CREAT, 0400)] OK
 42 [open(-, O_RDWR | O_CREAT, 0200)] OK
 43 [open(-, O_RDWR | O_CREAT, 0000)] OK
 44 [open(-, O_RDWR | O_CREAT | O_EXCL, 0600)] OK
 45 [open(+, O_RDWR | O_CREAT | O_EXCL, 0600)] OK
 46 [open(-, O_RDWR | O_CREAT | O_EXCL, 0000)] OK
 47 [open(+, O_RDWR | O_CREAT | O_EXCL, 0000)] OK
 48 [open_acc(O_RDONLY) mode: 0600 message: 'Success'] OK
 49 [open_acc(O_WRONLY) mode: 0600 message: 'Success'] OK
 50 [open_acc(O_RDWR) mode: 0600 message: 'Success'] OK
 51 [open_acc(O_RDONLY) mode: 0400 message: 'Success'] OK
 52 [open_acc(O_WRONLY) mode: 0200 message: 'Success'] OK
 53 [open(O_CREAT) in read-only directory] OK
 54 [open(O_CREAT | O_EXCL) in read-only directory] OK
 55 [open(O_CREAT | O_WRONLY) in read-only directory] OK
 56 [open(O_CREAT | O_TRUNC) in read-only directory] OK
1 tests failed
==================================== short test summary info =====================================
FAIL test/test_examples.py::test_passthrough[False-passthrough-False]
============================== 1 failed, 22 passed in 20.42 seconds ==============================
```

**Comment by Roay** [comment]
My environment:
```
# uname -a
Linux hadoop 4.18.15-1.el7.elrepo.x86_64 #1 SMP Thu Oct 18 10:19:42 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
# python3
Python 3.6.5 (default, Apr  3 2018, 15:27:59) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
```

**Comment by Nikratio** [comment]
Thanks for the report! I have no idea what might be going on here.. Is there anything special about this system? Do you have the same problem when you boot from e.g. a Debian Live CD? What's the output of `mount` on your system?

**Comment by Roay** [comment]
The system log has no output. And I haven't tested on other platforms at present.
How to understand` Is there anything special about this system`?

**Comment by 2994186010** [comment]
@Roay , have you solved the issue? I encounter the same problem as you.
