### ISSUE TITLE
Invoke mount fuse drop privilages test fails

### ISSUE THREAD

**Issue by srutownik** [libfuse/libfuse#357]
I am following your instructions to install libfuse 3.4.1
When I am running tests I am getting following results:

```
# sudo python3 -m pytest test/
================================================================================= test session starts ==================================================================================
platform linux -- Python 3.5.2, pytest-3.6.2, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
cachedir: test/.pytest_cache
rootdir: /home/mwawrzos/dev/tools/fuse-3.4.1/buld/test, inifile: pytest.ini
collected 41 items                                                                                                                                                                     

test/test_ctests.py::test_write_cache[False] PASSED                                                                                                                              [  2%]
test/test_ctests.py::test_write_cache[True] PASSED                                                                                                                               [  4%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                                                                                                                [  7%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                                                                                                                   [  9%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                                                                                                             [ 12%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                                                                                                               [ 14%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                                                                                                                  [ 17%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                                                                                                            [ 19%]
test/test_ctests.py::test_notify_file_size[True] PASSED                                                                                                                          [ 21%]
test/test_ctests.py::test_notify_file_size[False] PASSED                                                                                                                         [ 24%]
test/test_examples.py::test_hello[hello-options0-invoke_directly] PASSED                                                                                                         [ 26%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse] PASSED                                                                                                       [ 29%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges] FAILED                                                                                       [ 31%]

======================================================================================= FAILURES =======================================================================================
_____________________________________________________________ test_hello[hello-options0-invoke_mount_fuse_drop_privileges] _____________________________________________________________
Traceback (most recent call last):
  File "/home/mwawrzos/dev/tools/fuse-3.4.1/buld/test/test_examples.py", line 67, in test_hello
    wait_for_mount(mount_process, mnt_dir)
  File "/home/mwawrzos/dev/tools/fuse-3.4.1/buld/test/util.py", line 42, in wait_for_mount
    pytest.fail('file system process terminated prematurely')
  File "/usr/local/lib/python3.5/dist-packages/_pytest/outcomes.py", line 96, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: file system process terminated prematurely
--------------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------------
/bin/sh: 1: hello: Permission denied
=============================================================================== short test summary info ================================================================================
FAIL test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges]
========================================================================= 1 failed, 12 passed in 18.94 seconds =========================================================================
```

`hello` filesystem has following privilages:
```
# ls -alh example/hello
-rwxrwxr-x 1 mwawrzos mwawrzos 29K lut 12 16:52 example/hello
```

My environment:
```
# uname -a
Linux mwawrzos-dt 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
```

What can be wrong here?

**Comment by Smit-tay** [comment]
This is *exactly* the same issue which I am working on right now.

See my posting on the mailing list: https://sourceforge.net/p/fuse/mailman/message/36594196/

**Comment by Smit-tay** [comment]
WOW !!

In  my case I discovered that the directory permissions on /home/MYUSER were as follows:

[ME@MY-laptop build]$ ls -l /home
total 28
drwx------. 62 ME ME  4096 Feb 23 12:21 ME
drwx------.  2 root root 16384 Jan 19  2014 lost+found

This is significant because like most people, I do all my development within my home directory.

Running as UID=0,GID=0 (e.g  "sudo python -m pytest -s test/ --maxfail=99")

When mount.fuse drops all capabilities (and sets up the capabilities mask for the replacement process to ensure it doesn't regain them) it basically prevents UID=0,GID=0 from reading or traversing /home/ME.

mount.fuse launches "hello" (and others) via a shell instead of launching them directly:

`execl("/bin/sh", "/bin/sh", "-c", command, NULL);`

the shell cannot find "hello" in /home/ME/dev/FUSE/libfuse/build/example/hello.

If you change the permissions on /home/ME to be more permissive (e.g. `chmod o+rx`), then suddenly, (as if by magic) the test will be able to run - and hopefully pass.

**Comment by Nikratio** [comment]
Thanks for investigating! Closing this issue then.
