### ISSUE TITLE
test_passthrough_hp fails on some systems

### ISSUE THREAD

**Issue by jedai47** [libfuse/libfuse#499]
uname -a
Linux walid-MacBookPro 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

sudo python3 -m pytest test/
==================================================== test session starts ====================================================
platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/walid/build/test, inifile: pytest.ini
collected 43 items                                                                                                          

test/test_ctests.py::test_write_cache[False] PASSED                                                                   [  2%]
test/test_ctests.py::test_write_cache[True] PASSED                                                                    [  4%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                                                     [  6%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                                                        [  9%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                                                  [ 11%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                                                    [ 13%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                                                       [ 16%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                                                 [ 18%]
test/test_ctests.py::test_notify_file_size[True] PASSED                                                               [ 20%]
test/test_ctests.py::test_notify_file_size[False] PASSED                                                              [ 23%]
test/test_examples.py::test_hello[hello-options0-invoke_directly] PASSED                                              [ 25%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse] PASSED                                            [ 27%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges] PASSED                            [ 30%]
test/test_examples.py::test_hello[hello-options1-invoke_directly] PASSED                                              [ 32%]
test/test_examples.py::test_hello[hello-options1-invoke_mount_fuse] PASSED                                            [ 34%]
test/test_examples.py::test_hello[hello-options1-invoke_mount_fuse_drop_privileges] PASSED                            [ 37%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_directly] PASSED                                           [ 39%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_mount_fuse] PASSED                                         [ 41%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_mount_fuse_drop_privileges] PASSED                         [ 44%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_directly] PASSED                                           [ 46%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_mount_fuse] PASSED                                         [ 48%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_mount_fuse_drop_privileges] PASSED                         [ 51%]
test/test_examples.py::test_passthrough[False-passthrough-False] PASSED                                               [ 53%]
test/test_examples.py::test_passthrough[False-passthrough-True] SKIPPED                                               [ 55%]
test/test_examples.py::test_passthrough[False-passthrough_fh-False] PASSED                                            [ 58%]
test/test_examples.py::test_passthrough[False-passthrough_fh-True] SKIPPED                                            [ 60%]
test/test_examples.py::test_passthrough[False-passthrough_ll-False] PASSED                                            [ 62%]
test/test_examples.py::test_passthrough[False-passthrough_ll-True] PASSED                                             [ 65%]
test/test_examples.py::test_passthrough[True-passthrough-False] PASSED                                                [ 67%]
test/test_examples.py::test_passthrough[True-passthrough-True] SKIPPED                                                [ 69%]
test/test_examples.py::test_passthrough[True-passthrough_fh-False] PASSED                                             [ 72%]
test/test_examples.py::test_passthrough[True-passthrough_fh-True] SKIPPED                                             [ 74%]
test/test_examples.py::test_passthrough[True-passthrough_ll-False] PASSED                                             [ 76%]
test/test_examples.py::test_passthrough[True-passthrough_ll-True] PASSED                                              [ 79%]
test/test_examples.py::test_passthrough_hp[False] PASSED                                                              [ 81%]
test/test_examples.py::test_passthrough_hp[True] FAILED                                                               [ 83%]

========================================================= FAILURES ==========================================================
_________________________________________________ test_passthrough_hp[True] _________________________________________________
Traceback (most recent call last):
  File "/home/walid/build/test/test_examples.py", line 202, in test_passthrough_hp
    tst_rmdir(src_dir, mnt_dir)
  File "/home/walid/build/test/test_examples.py", line 417, in tst_rmdir
    assert name in os.listdir(mnt_dir)
AssertionError: assert 'testfile_200' in ['testfile_195', 'testfile_196', 'testfile_198', 'testfile_199', 'testfile_197', 'testfile_194']
 +  where ['testfile_195', 'testfile_196', 'testfile_198', 'testfile_199', 'testfile_197', 'testfile_194'] = <built-in function listdir>('/tmp/tmph9hb3buu/mnt')
 +    where <built-in function listdir> = os.listdir
===================================================== warnings summary ======================================================
/home/walid/.local/lib/python3.6/site-packages/_pytest/mark/structures.py:327
/home/walid/.local/lib/python3.6/site-packages/_pytest/mark/structures.py:327
  /home/walid/.local/lib/python3.6/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.uses_fuse - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================== short test summary info ==================================================
SKIPPED [4] /home/walid/build/test/test_examples.py:126: example does not support writeback caching
FAILED test/test_examples.py::test_passthrough_hp[True] - AssertionError: assert 'testfile_200' in ['testfile_195', 'testf...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================== 1 failed, 31 passed, 4 skipped, 2 warnings in 29.03s ====================================

**Comment by ne0ark** [comment]
I am running into same issue I wonder its because kernel doesn't include FUSE (Filesystem in Userspace) support [CONFIG_FUSE_FS].

**Comment by MartinMa28** [comment]
I have the same issue when building the released 3.9 version.

**Comment by Nikratio** [comment]
Thanks for the report! No, this wouldn't be caused by not having FUSE support in the kernel (the test would be skipped or you'd get an entirely different error). I don't have time in the foreseeable future to look into this, but I'll keep the bug open.

**Comment by matthiasgoergens** [comment]
For what it's worth, this test passes on my machine `Linux spider 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 GNU/Linux` on latest master.

**Comment by Nikratio** [comment]
Yeah, it also consistently passes in the CI. There's got to be something special about the systems where it fails...

**Comment by bsbernd** [comment]
Should be all fixed in the mean time.
