### ISSUE TITLE
test/test_examples.py::test_passthrough_hp regression from 3.12 to 3.14

### ISSUE THREAD

**Issue by keithlee96** [libfuse/libfuse#745]
The tests would all pass on version 3.12.0 with Ubuntu 22.04.2. However, when I tried to install 3.14 on Ubuntu 22.04.2, the tests failed with this error:
```
fuse-3.14.0/build$ sudo python3 -m pytest test/
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: ~/Downloads/fuse-3.14.0/build/test, configfile: pytest.ini
collected 50 items                                                             

test/test_ctests.py::test_write_cache[False] PASSED                      [  2%]
...
test/test_examples.py::test_passthrough[True-passthrough_ll-True] PASSED [ 80%]
test/test_examples.py::test_passthrough_hp[False] FAILED                 [ 82%]

=================================== FAILURES ===================================
__________________________ test_passthrough_hp[False] __________________________
Traceback (most recent call last):
  File "~Downloads/fuse-3.14.0/build/test/test_examples.py", line 234, in test_passthrough_hp
    tst_utimens(mnt_dir, ns_tol=1000)
  File "~/Downloads/fuse-3.14.0/build/test/test_examples.py", line 730, in tst_utimens
    os.utime(filename, None, ns=(atime_ns, mtime_ns))
OSError: [Errno 95] Operation not supported
=============================== warnings summary ===============================
test/conftest.py:17
  ~/Downloads/fuse-3.14.0/build/test/conftest.py:17: PytestDeprecationWarning: The hookimpl pytest_pyfunc_call uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(hookwrapper=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    @pytest.mark.hookwrapper

test/test_ctests.py:12
  ~/Downloads/fuse-3.14.0/build/test/test_ctests.py:12: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion

test_examples.py::test_printcap
  /usr/local/lib/python3.10/dist-packages/_pytest/python.py:199: PytestReturnNotNoneWarning: Expected None, but test_examples.py::test_printcap returned ((7, 36), {'FUSE_CAP_POSIX_ACL', 'FUSE_CAP_SPLICE_MOVE', 'FUSE_CAP_EXPORT_SUPPORT', 'FUSE_CAP_ASYNC_DIO', 'FUSE_CAP_ASYNC_READ', 'FUSE_CAP_DONT_MASK', 'FUSE_CAP_FLOCK_LOCKS', 'FUSE_CAP_CACHE_SYMLINKS', 'FUSE_CAP_NO_OPENDIR_SUPPORT', 'FUSE_CAP_PARALLEL_DIROPS', 'FUSE_CAP_SPLICE_WRITE', 'FUSE_CAP_READDIRPLUS_AUTO', 'FUSE_CAP_NO_OPEN_SUPPORT', 'FUSE_CAP_READDIRPLUS', 'FUSE_CAP_IOCTL_DIR', 'FUSE_CAP_POSIX_LOCKS', 'FUSE_CAP_SPLICE_READ', 'FUSE_CAP_AUTO_INVAL_DATA', 'FUSE_CAP_EXPLICIT_INVAL_DATA', 'FUSE_CAP_WRITEBACK_CACHE', 'FUSE_CAP_ATOMIC_O_TRUNC'}), which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
SKIPPED [6] test/test_examples.py:143: example does not support writeback caching
FAILED test/test_examples.py::test_passthrough_hp[False] - OSError: [Errno 95] Operation not supported
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
============= 1 failed, 34 passed, 6 skipped, 3 warnings in 31.06s =============

```
Note, I tried 3.12 after and it worked fine:
```
fuse-3.12.0/build$ sudo python3 -m pytest test/
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.10.6, pytest-7.2.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /path/fuse-3.12.0/build/test, configfile: pytest.ini
collected 47 items                                                                                                                                                                      

test/test_ctests.py::test_write_cache[False] PASSED                                                                                                                               [  2%]
test/test_ctests.py::test_write_cache[True] PASSED                                                                                                                                [  4%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                                                                                                                 [  6%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                                                                                                                    [  8%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                                                                                                              [ 10%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                                                                                                                [ 12%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                                                                                                                   [ 14%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                                                                                                             [ 17%]
test/test_ctests.py::test_notify_file_size[True] PASSED                                                                                                                           [ 19%]
test/test_ctests.py::test_notify_file_size[False] PASSED                                                                                                                          [ 21%]
test/test_examples.py::test_printcap PASSED                                                                                                                                       [ 23%]
test/test_examples.py::test_hello[hello-options0-invoke_directly] PASSED                                                                                                          [ 25%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse] PASSED                                                                                                        [ 27%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges] PASSED                                                                                        [ 29%]
test/test_examples.py::test_hello[hello-options1-invoke_directly] PASSED                                                                                                          [ 31%]
test/test_examples.py::test_hello[hello-options1-invoke_mount_fuse] PASSED                                                                                                        [ 34%]
test/test_examples.py::test_hello[hello-options1-invoke_mount_fuse_drop_privileges] PASSED                                                                                        [ 36%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_directly] PASSED                                                                                                       [ 38%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_mount_fuse] PASSED                                                                                                     [ 40%]
test/test_examples.py::test_hello[hello_ll-options0-invoke_mount_fuse_drop_privileges] PASSED                                                                                     [ 42%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_directly] PASSED                                                                                                       [ 44%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_mount_fuse] PASSED                                                                                                     [ 46%]
test/test_examples.py::test_hello[hello_ll-options1-invoke_mount_fuse_drop_privileges] PASSED                                                                                     [ 48%]
test/test_examples.py::test_passthrough[False-passthrough-False] PASSED                                                                                                           [ 51%]
test/test_examples.py::test_passthrough[False-passthrough-True] SKIPPED (example does not support writeback caching)                                                              [ 53%]
test/test_examples.py::test_passthrough[False-passthrough_plus-False] PASSED                                                                                                      [ 55%]
test/test_examples.py::test_passthrough[False-passthrough_plus-True] SKIPPED (example does not support writeback caching)                                                         [ 57%]
test/test_examples.py::test_passthrough[False-passthrough_fh-False] PASSED                                                                                                        [ 59%]
test/test_examples.py::test_passthrough[False-passthrough_fh-True] SKIPPED (example does not support writeback caching)                                                           [ 61%]
test/test_examples.py::test_passthrough[False-passthrough_ll-False] PASSED                                                                                                        [ 63%]
test/test_examples.py::test_passthrough[False-passthrough_ll-True] PASSED                                                                                                         [ 65%]
test/test_examples.py::test_passthrough[True-passthrough-False] PASSED                                                                                                            [ 68%]
test/test_examples.py::test_passthrough[True-passthrough-True] SKIPPED (example does not support writeback caching)                                                               [ 70%]
test/test_examples.py::test_passthrough[True-passthrough_plus-False] PASSED                                                                                                       [ 72%]
test/test_examples.py::test_passthrough[True-passthrough_plus-True] SKIPPED (example does not support writeback caching)                                                          [ 74%]
test/test_examples.py::test_passthrough[True-passthrough_fh-False] PASSED                                                                                                         [ 76%]
test/test_examples.py::test_passthrough[True-passthrough_fh-True] SKIPPED (example does not support writeback caching)                                                            [ 78%]
test/test_examples.py::test_passthrough[True-passthrough_ll-False] PASSED                                                                                                         [ 80%]
test/test_examples.py::test_passthrough[True-passthrough_ll-True] PASSED                                                                                                          [ 82%]
test/test_examples.py::test_passthrough_hp[False] PASSED                                                                                                                          [ 85%]
test/test_examples.py::test_passthrough_hp[True] PASSED                                                                                                                           [ 87%]
test/test_examples.py::test_ioctl PASSED                                                                                                                                          [ 89%]
test/test_examples.py::test_poll PASSED                                                                                                                                           [ 91%]
test/test_examples.py::test_null PASSED                                                                                                                                           [ 93%]
test/test_examples.py::test_notify_inval_entry[True] PASSED                                                                                                                       [ 95%]
test/test_examples.py::test_notify_inval_entry[False] PASSED                                                                                                                      [ 97%]
test/test_examples.py::test_cuse PASSED                                                                                                                                           [100%]

=================================================================================== warnings summary ====================================================================================
test/conftest.py:17
  /fuse-3.12.0/build/test/conftest.py:17: PytestDeprecationWarning: The hookimpl pytest_pyfunc_call uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(hookwrapper=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    @pytest.mark.hookwrapper

test/test_ctests.py:12
  /fuse-3.12.0/build/test/test_ctests.py:12: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion

test_examples.py::test_printcap
  /usr/local/lib/python3.10/dist-packages/_pytest/python.py:199: PytestReturnNotNoneWarning: Expected None, but test_examples.py::test_printcap returned ((7, 36), {'FUSE_CAP_ATOMIC_O_TRUNC', 'FUSE_CAP_POSIX_ACL', 'FUSE_CAP_FLOCK_LOCKS', 'FUSE_CAP_EXPLICIT_INVAL_DATA', 'FUSE_CAP_WRITEBACK_CACHE', 'FUSE_CAP_SPLICE_MOVE', 'FUSE_CAP_PARALLEL_DIROPS', 'FUSE_CAP_DONT_MASK', 'FUSE_CAP_EXPORT_SUPPORT', 'FUSE_CAP_READDIRPLUS', 'FUSE_CAP_ASYNC_DIO', 'FUSE_CAP_NO_OPEN_SUPPORT', 'FUSE_CAP_ASYNC_READ', 'FUSE_CAP_SPLICE_READ', 'FUSE_CAP_NO_OPENDIR_SUPPORT', 'FUSE_CAP_READDIRPLUS_AUTO', 'FUSE_CAP_SPLICE_WRITE', 'FUSE_CAP_AUTO_INVAL_DATA', 'FUSE_CAP_POSIX_LOCKS', 'FUSE_CAP_CACHE_SYMLINKS', 'FUSE_CAP_IOCTL_DIR'}), which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================ short test summary info ================================================================================
SKIPPED [6] test/test_examples.py:143: example does not support writeback caching
====================================================================== 41 passed, 6 skipped, 3 warnings in 43.06s =======================================================================

```
I suspect this test got broken by one of the passthrough_hp changes between 3.12.0 and 3.14.0.

**Comment by Nikratio** [comment]
Thanks for the report! This should be fixed in commit df2cde2.
