### ISSUE TITLE
failed to run pytest under ubuntu

### ISSUE THREAD

**Issue by gaowayne** [libfuse/libfuse#795]
PLEASE READ BEFORE REPORTING AN ISSUE

libfuse does not have any active, regular contributors or developers.  The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. When reporting bugs, please understand that unless you are including a pull request or are reporting a critical issue, you will probably not get a response.

To prevent the issue tracker from being flooded with issues that no-one is intending to work on, and to give more visibility to critical issues that users should be aware of and that most urgently need attention, I will also close most bug reports once they've been inactive for a while.

Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. Unfortunately, libfuse is a purely volunteer driven project, and at the moment there simply aren't any volunteers.

====
OS:
```
wayne@wayne-virtual-machine:~/wayne/libfuse/build$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

error log:
```
wayne@wayne-virtual-machine:~/wayne/libfuse/build$ python3 -m pytest test/
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/wayne/wayne/libfuse/build/test
configfile: pytest.ini
collected 0 items / 1 error                                                                                                                                                                               

================================================================================================= ERRORS ==================================================================================================
_____________________________________________________________________________________ ERROR collecting test_ctests.py _____________________________________________________________________________________
ImportError while importing test module '/home/wayne/wayne/libfuse/build/test/test_ctests.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_ctests.py:12: in <module>
    from looseversion import LooseVersion
E   ModuleNotFoundError: No module named 'looseversion'
============================================================================================ warnings summary =============================================================================================
../../../../../usr/local/lib/python3.10/dist-packages/_pytest/cacheprovider.py:433
  /usr/local/lib/python3.10/dist-packages/_pytest/cacheprovider.py:433: PytestCacheWarning: cache could not write path /home/wayne/wayne/libfuse/build/test/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../../../../../usr/local/lib/python3.10/dist-packages/_pytest/stepwise.py:56
  /usr/local/lib/python3.10/dist-packages/_pytest/stepwise.py:56: PytestCacheWarning: cache could not write path /home/wayne/wayne/libfuse/build/test/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================================= short test summary info =========================================================================================
ERROR test/test_ctests.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================== 2 warnings, 1 error in 0.01s =======================================================================================

```

**Comment by marcinsulikowski** [comment]
You didn't install Python libraries needed to run the tests – see https://github.com/libfuse/libfuse/blob/master/test/ci-install.sh. Run:
```
python3 -m pip install looseversion
```
to install `looseversion`.

**Comment by gaowayne** [comment]
it works. :) man, I am already use root to run test, why I still get permission problem below
```
root@wayne-virtual-machine:/home/wayne/wayne/libfuse/build# sudo python3 -m pytest test/
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/wayne/wayne/libfuse/build/test
configfile: pytest.ini
collected 53 items                                                                                                                                                                                        

test/test_ctests.py::test_write_cache[False] PASSED                                                                                                                                                 [  1%]
test/test_ctests.py::test_write_cache[True] PASSED                                                                                                                                                  [  3%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                                                                                                                                   [  5%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                                                                                                                                      [  7%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                                                                                                                                [  9%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                                                                                                                                  [ 11%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                                                                                                                                     [ 13%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                                                                                                                               [ 15%]
test/test_ctests.py::test_notify_file_size[True] PASSED                                                                                                                                             [ 16%]
test/test_ctests.py::test_notify_file_size[False] PASSED                                                                                                                                            [ 18%]
test/test_custom_io.py::test_hello_uds PASSED                                                                                                                                                       [ 20%]
test/test_examples.py::test_printcap PASSED                                                                                                                                                         [ 22%]
test/test_examples.py::test_hello[hello-options0-invoke_directly] PASSED                                                                                                                            [ 24%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse] PASSED                                                                                                                          [ 26%]
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges] FAILED                                                                                                          [ 28%]

================================================================================================ FAILURES =================================================================================================
______________________________________________________________________ test_hello[hello-options0-invoke_mount_fuse_drop_privileges] _______________________________________________________________________
Traceback (most recent call last):
  File "/home/wayne/wayne/libfuse/build/test/test_examples.py", line 96, in test_hello
    wait_for_mount(mount_process, mnt_dir)
  File "/home/wayne/wayne/libfuse/build/test/util.py", line 44, in wait_for_mount
    pytest.fail('file system process terminated prematurely')
  File "/usr/local/lib/python3.10/dist-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: file system process terminated prematurely
------------------------------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------------------------------
/bin/sh: 1: hello: Permission denied
========================================================================================= short test summary info =========================================================================================
FAILED test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges] - Failed: file system process terminated prematurely
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================== 1 failed, 14 passed in 20.41s ======================================================================================
root@wayne-virtual-machine:/home/wayne/wayne/libfuse/build# 

```

**Comment by Nikratio** [comment]
'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.
